### ISSUE TITLE
chrome android is showing accuracy to a ridiculous level of precision

### ISSUE THREAD

**Issue by kevinmarks** [rjp44/locus-plus#7]
![Screenshot_20210513-141049](https://user-images.githubusercontent.com/99008/118130442-43c0cb80-b3f5-11eb-9751-402e000f53b4.jpeg)
Looks like they return a float, so you should round it for display.

**Comment by rjp44** [comment]
Think this was already done in d40e22ce5d0263c679a74a5faf5e457f6e972cf6 and should have been pushed to live by CI.

Because of the way that PWAs work, your implementation gets cached until the next time you restart the App. It is necessary to close *all* browser tabs, and all home screen launches of the PWA before it will re-fetch a new implementation.

**Comment by kevinmarks** [comment]
Aaron found a way to force a Service Worker to remove itself https://medium.com/@nekrtemplar/self-destroying-serviceworker-73d62921d717

**Comment by rjp44** [comment]
It is the serviceWorker which is responsible for the offline functionality of the App. If we take that away then that is great for development but stops things working on the top of a hill when you have no connectivity.

**Comment by kevinmarks** [comment]
looks good now
